(function(g){var window=this;var H4=function(a,b,c){var d=b.va();g.L(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.kc(c?c:"mqdefault.jpg");var f=b instanceof g.aC&&b.lengthSeconds?g.vM(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.RD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.aC?b.sa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.jj||g.gN("\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c $TITLE",
{TITLE:b.title}),duration:f,url:b.fi(),is_live:l,is_list:k,is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.TD&&(d.playlist_length=b.getLength());a.update(d)},I4=function(a,b){g.Ju.call(this,{F:"div",
X:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},J4=function(a){g.W.call(this,{F:"div",
X:["ytp-upnext","ytp-player-content"],N:{"aria-label":"{{aria_label}}"},L:[{F:"div",I:"ytp-cued-thumbnail-overlay-image",N:{style:"{{background}}"}},{F:"span",I:"ytp-upnext-top",L:[{F:"span",I:"ytp-upnext-header",W:"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},{F:"span",I:"ytp-upnext-title",W:"{{title}}"},{F:"span",I:"ytp-upnext-author",W:"{{author}}"}]},{F:"a",I:"ytp-upnext-autoplay-icon",N:{role:"button",href:"{{url}}","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
L:[{F:"svg",N:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},L:[{F:"circle",I:"ytp-svg-autoplay-circle",N:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",I:"ytp-svg-autoplay-ring",N:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",I:"ytp-svg-fill",N:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",I:"ytp-upnext-bottom",
L:[{F:"span",I:"ytp-upnext-cancel"},{F:"span",I:"ytp-upnext-paused",W:"\u0410\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043f\u0440\u0438\u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e."}]}]});this.C=null;var b=this.u["ytp-upnext-cancel"];this.C=new g.W({F:"button",X:["ytp-upnext-cancel-button","ytp-button"],N:{tabindex:"0","aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},
W:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.H(this,this.C);this.C.ga("click",this.tI,this);this.C.o(b);this.w=a;this.K=this.u["ytp-svg-autoplay-ring"];this.G=this.D=this.A=this.B=null;this.H=new g.J(this.Kl,5E3,this);g.H(this,this.H);this.J=0;this.M(this.u["ytp-upnext-autoplay-icon"],"click",this.gK);this.ny();this.M(a,"autonavvisibility",this.ny);this.M(a,"mdxnowautoplaying",this.yJ);this.M(a,"mdxautoplaycanceled",this.zJ);this.M(a,"mdxautoplayupnext",this.GA);3==this.w.getPresentingPlayerType()&&
(a=(a=g.HK(g.AK(this.w)))?a.ZC():null)&&this.GA(a)},K4=function(a,b){if(!a.A){g.Go("a11y-announce","\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 "+a.B.title);
a.J=(0,g.Kq)();a.A=new g.J((0,g.x)(a.Po,a,b),25);a.Po(b);var c=b||g.S(a.w.O().experiments,"autoplay_time")||1E4;a.w.la("onAutonavCoundownStarted",c)}g.jn(a.element,"ytp-upnext-autoplay-paused")},M4=function(a){L4(a);
a.J=(0,g.Kq)();a.Po();g.K(a.element,"ytp-upnext-autoplay-paused")},L4=function(a){a.A&&(a.A.dispose(),a.A=null)},N4=function(a,b){b=void 0===b?!1:b;
if(g.R(a.w.O().experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.B.va(),a.Kl(),a.D=new Notification("\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435",{body:c.title,icon:c.kc()}),a.G=a.M(a.D,"click",a.XJ),a.H.start())}L4(a);a.w.nextVideo(!1,b)},O4=function(a){I4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.w=new g.W({F:"div",I:"ytp-subscribe-card",L:[{F:"img",I:"ytp-author-image",N:{src:b.Od}},{F:"div",I:"ytp-subscribe-card-right",L:[{F:"div",I:"ytp-author-name",W:b.author},{F:"div",I:"html5-subscribe-button-container"}]}]});g.H(this,this.w);this.w.o(this.element);this.A=new g.yR("\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u0442\u044c\u0441\u044f",null,"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0443",null,!0,!1,b.Pf,b.subscribed,
"trailer-endscreen",null,null,a);g.H(this,this.A);this.A.o(this.w.u["html5-subscribe-button-container"]);this.hide()},P4=function(a){var b=a.O(),c=g.Ks||g.dg?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.W.call(this,{F:"a",X:e,N:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{F:"div",I:"ytp-videowall-still-image",N:{style:"{{background}}"}},{F:"span",I:"ytp-videowall-still-info",L:[{F:"span",I:"ytp-videowall-still-info-bg",L:[{F:"span",I:"ytp-videowall-still-info-content",N:c,L:[{F:"span",I:"ytp-videowall-still-info-title",W:"{{title}}"},{F:"span",I:"ytp-videowall-still-info-author",
W:"{{author_and_views}}"},{F:"span",I:"ytp-videowall-still-info-live",W:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{F:"span",I:"ytp-videowall-still-info-duration",W:"{{duration}}"}]}]}]},{F:"span",X:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],L:[{F:"span",I:"ytp-videowall-still-listlabel-icon"},"\u041f\u043b\u0435\u0439\u043b\u0438\u0441\u0442",{F:"span",I:"ytp-videowall-still-listlabel-length",L:[" (",{F:"span",W:"{{playlist_length}}"},")"]}]},{F:"span",X:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],L:[{F:"span",I:"ytp-videowall-still-listlabel-mix-icon"},"\u041c\u0438\u043a\u0441",{F:"span",I:"ytp-videowall-still-listlabel-length",W:" (50+)"}]}]});this.C=d;this.w=a;this.A=null;this.B=new g.Q(this);g.H(this,this.B);this.ga("click",this.G);this.ga("keypress",this.H);this.B.M(a,"videodatachange",this.D);g.aL(a,this.element,this);this.D()},Q4=function(a){g.cL(a.w,a.element);
var b=a.A.va().videoId,c=a.A.getPlaylistId();g.XT(a.w.app,b,a.A.Fb,c,void 0,void 0)},R4=function(a){I4.call(this,a,"videowall-endscreen");
this.G=a;this.D=0;this.A=[];this.H=this.S=this.C=null;this.J=this.V=!1;this.T=null;this.B=new g.Q(this);g.H(this,this.B);this.K=new g.J(g.Na(g.K,this.element,"ytp-show-tiles"),0);g.H(this,this.K);var b=new g.W({F:"button",X:["ytp-button","ytp-endscreen-previous"],N:{"aria-label":"\u041d\u0430\u0437\u0430\u0434"},L:[g.DM()]});g.H(this,b);b.o(this.element);b.ga("click",this.GF,this);this.P=new g.Du({F:"div",I:"ytp-endscreen-content"});g.H(this,this.P);this.P.o(this.element);b=new g.W({F:"button",X:["ytp-button",
"ytp-endscreen-next"],N:{"aria-label":"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},L:[g.EM()]});g.H(this,b);b.o(this.element);b.ga("click",this.FF,this);this.w=new J4(a);g.H(this,this.w);g.YK(this.player,this.w.element,4);this.hide()},S4=function(a){return g.ZK(a.player)&&a.hu()&&!a.H},T4=function(a,b){return(0,g.ee)(b.suggestions,function(c){c=g.hN(a.G.O(),c);
g.H(a,c);return c})},U4=function(a){var b=a.Qq();
b!=a.V&&(a.V=b,a.player.R("autonavvisibility"))},W4=function(a){g.lQ.call(this,a);
this.o=null;this.u=new g.Q(this);g.H(this,this.u);this.w=a.O();V4(a)?this.o=new R4(this.player):this.w.Ka?this.o=new O4(this.player):this.o=new I4(this.player);g.H(this,this.o);g.YK(this.player,this.o.element,4);this.Jz();this.u.M(a,"videodatachange",this.Jz,this);this.u.M(a,g.QD("endscreen"),this.ME,this);this.u.M(a,"crx_endscreen",this.NE,this)},V4=function(a){a=a.O();
return a.Ha&&!a.Ka};
g.r(I4,g.Ju);I4.prototype.create=function(){this.created=!0};
I4.prototype.destroy=function(){this.created=!1};
I4.prototype.hu=function(){return!1};
I4.prototype.Qq=function(){return!1};g.r(J4,g.W);g.h=J4.prototype;g.h.Kl=function(){this.D&&(this.H.stop(),this.Ta(this.G),this.G=null,this.D.close(),this.D=null)};
g.h.ny=function(){g.Iu(this,g.BK(this.w))};
g.h.XJ=function(){window.focus();this.Kl()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.Po=function(a){a=a||g.S(this.w.O().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.Kq)()-this.J,a);a=Math.min(b/a,1);this.K.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.w.getPresentingPlayerType()?N4(this,!0):this.A&&this.A.start()};
g.h.gK=function(a){!g.Wd(this.C.element,g.$q(a))&&g.oN(a,this.w)&&N4(this)};
g.h.tI=function(){g.DK(this.w,!0)};
g.h.yJ=function(a){this.w.getPresentingPlayerType();this.show();K4(this,a)};
g.h.GA=function(a){this.w.getPresentingPlayerType();this.B&&this.B.va().videoId==a.va().videoId||(this.B=a,H4(this,a,"hqdefault.jpg"))};
g.h.zJ=function(){this.w.getPresentingPlayerType();L4(this);this.hide()};
g.h.Y=function(){L4(this);this.Kl();g.W.prototype.Y.call(this)};g.r(O4,I4);g.r(P4,g.W);P4.prototype.G=function(a){g.oN(a,this.w,this.C,this.A.Fb||void 0)&&Q4(this)};
P4.prototype.H=function(a){switch(a.keyCode){case 13:case 32:g.er(a)||(Q4(this),g.dr(a))}};
P4.prototype.D=function(){var a=this.w.getVideoData(),b=this.w.O();this.C=a.ac?!1:b.u};g.r(R4,I4);g.h=R4.prototype;g.h.create=function(){I4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.C=T4(this,a),this.S=a);this.Nf();this.B.M(this.player,"appresize",this.Nf);this.B.M(this.player,"onVideoAreaChange",this.Nf);this.B.M(this.player,"videodatachange",this.HF);this.B.M(this.player,"autonavchange",this.Rq);this.B.M(this.player,"autonavcancel",this.EF);a=this.S.autonavState;a!=this.T&&this.Rq(a);this.B.M(this.element,"transitionend",this.xL)};
g.h.destroy=function(){g.Vs(this.B);g.zi(this.A);this.A=[];this.C=null;I4.prototype.destroy.call(this);g.jn(this.element,"ytp-show-tiles");this.K.stop();this.T=this.S.autonavState};
g.h.hu=function(){return 1!=this.S.autonavState};
g.h.show=function(){I4.prototype.show.call(this);g.jn(this.element,"ytp-show-tiles");this.player.O().o?g.Zm(this.K):this.K.start();(this.J||this.H&&this.H!=this.S.clientPlaybackNonce)&&g.DK(this.player,!1);S4(this)?(U4(this),2==this.S.autonavState?g.R(this.player.O().experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?N4(this.w,!0):K4(this.w):3==this.S.autonavState&&M4(this.w)):(g.DK(this.player,!0),U4(this))};
g.h.hide=function(){I4.prototype.hide.call(this);M4(this.w);U4(this)};
g.h.xL=function(a){g.$q(a)==this.element&&this.Nf()};
g.h.Nf=function(){if(this.C&&this.C.length){g.K(this.element,"ytp-endscreen-paginate");var a=g.PK(this.G,!0,this.G.isFullscreen()),b=g.gD(this.G);b&&(b=b.Rb()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,t=e/2,u=b<=f-2&&n>=t*m,y=e<=k-2&&n>=q*m;if((q+1)/t*d/c>c/(q/(t+1)*d)&&y)n-=q*m,e+=2;else if(u)n-=t*m,b+=2;else if(y)n-=
q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.ld(a.width/m||1,1,1.21);n*=g.ld(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.P.element;g.sg(a,m,n);g.ag(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.w;f=this.C[0];c.B=f;H4(c,f,"hqdefault.jpg");g.L(this.element,"ytp-endscreen-takeover",S4(this));U4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=
c,t=0,d&&f>=b-2&&k>=e-2?t=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(t=2):t=2),q=g.md(q+this.D,l),0!=t){u=this.A[c];u||(u=new P4(this.player),this.A[c]=u,a.appendChild(u.element));y=Math.floor(n*k/e);var B=Math.floor(m*f/b),C=Math.floor(n*(k+t)/e)-y-4,G=Math.floor(m*(f+t)/b)-B-4;g.ig(u.element,B,y);g.sg(u.element,G,C);g.ag(u.element,"transitionDelay",(k+f)/20+"s");g.L(u.element,"ytp-videowall-still-mini",1==t);g.L(u.element,"ytp-videowall-still-large",2<t);t=u;q=this.C[q];t.A!=q&&(t.A=q,H4(t,q,g.gn(t.element,
"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg"),(q=(q=q.Fb)&&q.itct)&&g.bL(t.w,t.element,q));c++}g.L(this.element,"ytp-endscreen-paginate",c<l);for(b=this.A.length-1;b>=c;b--)e=this.A[b],g.Sd(e.element),g.yi(e);this.A.length=c}};
g.h.HF=function(){var a=this.player.getVideoData();this.S!=a&&(this.D=0,this.C=T4(this,a),this.S=a,this.Nf())};
g.h.FF=function(){this.D+=this.A.length;this.Nf()};
g.h.GF=function(){this.D-=this.A.length;this.Nf()};
g.h.eE=function(){return!!this.w.A};
g.h.Rq=function(a){1==a?(this.J=!1,this.H=this.S.clientPlaybackNonce,L4(this.w),this.Ga()&&this.Nf()):(this.J=!0,this.Ga()&&S4(this)&&(2==a?K4(this.w):3==a&&M4(this.w)))};
g.h.EF=function(a){if(a){for(a=0;a<this.A.length;a++)g.dL(this.G,this.A[a].element,!0);this.Rq(1)}else this.H=null,this.J=!1;this.Nf()};
g.h.Qq=function(){return this.Ga()&&S4(this)};g.r(W4,g.lQ);g.h=W4.prototype;g.h.Sw=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!V4(this.player)||b;a=a.Nh||g.fz(a.Ma);var c=g.sT(this.player.app);return b&&!a&&!c};
g.h.Rw=function(){return this.o.Qq()};
g.h.WD=function(){return this.Rw()?this.o.eE():!1};
g.h.Y=function(){g.sR(this.player.app,"endscreen",void 0);g.lQ.prototype.Y.call(this)};
g.h.load=function(){g.lQ.prototype.load.call(this);this.o.show()};
g.h.unload=function(){g.lQ.prototype.unload.call(this);this.o.hide();this.o.destroy()};
g.h.ME=function(a){this.Sw()&&(this.o.created||this.o.create(),"load"==a.getId()&&this.load())};
g.h.NE=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Jz=function(){g.sR(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.ND(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.H(this,a);var b=new g.ND(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.H(this,b);g.UK(this.player,[a,b])};g.BQ.endscreen=W4;})(_yt_player);
